server:
  port: 8082
spring:
  profiles:
    active: dev

#person:
#  name: haha
---

spring:
  profiles: dev
server:
  port: 8085

person:
  name: 李四
---
spring:
  profiles: prod
server:
  port: 8086

#person:
#  name: 丁柳